### ISSUE TITLE
Environment for running try-a-bot activities

### ISSUE THREAD

**Issue by psychemedia** [RobInLabUJI/try-a-bot#1]
Hi

I was wondering whether there is a Dockerfile or Vagrantfile anywhere that builds an environment that the `try-a-bot` activities can run in?

I was thinking of trying to make them available in the context of a JupyterHub environment, perhaps even a customised [Littlest Jupyterhub (TLJH)](https://tljh.jupyter.org/en/latest/) environment.

**Comment by ecervera** [comment]
No, there isn't, because when the activities were developed, the simulator (Webots) was proprietary and closed-source software.
It would be great to run it in JupyterHub. Unfortunately I can't devote much time to this for now.
Good luck!

**Comment by ecervera** [comment]
We have set up a VirtualBox environment for running Try-a-Bot.
Since Webots has gone open source, no license is necessary :-)
More information in:
[https://sites.google.com/uji.es/try-a-bot/virtual-machine](https://sites.google.com/uji.es/try-a-bot/virtual-machine)

**Comment by psychemedia** [comment]
@ecervera Very nice:-) Is there a vagrantfile or similar for building/launching the VM? Or maybe even a Dockerfile? Could be v interesting if webots ran in a container via jupyter server proxy or https://github.com/ideonate/jhsingle-native-proxy that could be launched via JupyterHub?

**Comment by ecervera** [comment]
@psychemedia There is no vagrantfile, since this machine was manually built on VirtualBox some time ago for an online course. I have decided to make it now available to the public because of Webots becoming free open source. 
However, a dockerfile would be great, I'm thinking of building an image with Webots and Jupyter, hope to have something working soon.

**Comment by psychemedia** [comment]
@ecervera let me know if there's anything I can help with Dockerfile wise. Starting from a binder base box or using a recipe that works with repo2docker may simplify integrations with other parts of Jupyter ecosystem.

**Comment by ecervera** [comment]
@psychemedia thank you for your willingness to help! 

I have just stumbled upon a very interesting information about Webots and Docker:
[https://github.com/cyberbotics/webots/wiki/Docker](https://github.com/cyberbotics/webots/wiki/Docker)

It would be great to merge that recipe with:

* [a jupyter image](https://jupyter-docker-stacks.readthedocs.io/en/latest/)
* [a ROS image](https://hub.docker.com/_/ros) (since I use the webots_ros controller for interfacing with the simulated robots)

Any help is appreciated.

**Comment by ecervera** [comment]
@psychemedia I have prepared a first version here:
[https://github.com/RobInLabUJI/Webots-Docker](https://github.com/RobInLabUJI/Webots-Docker)
It compiles and runs, but can't get the 3D scene in the browser yet.

**Comment by psychemedia** [comment]
Sounds a great start... Unfortunately, I'm away from computers atm on leave... Will take a look when I get back home/online properly...

**Comment by psychemedia** [comment]
It's not a quick build is it?! Do you have a prebuilt image I could pull
down?

**Comment by ecervera** [comment]
Indeed! It's quite a big upload too! 
I'm pushing it now, hope it will be available in a couple of hours at [https://hub.docker.com/repository/docker/ecervera/webots-docker](https://hub.docker.com/repository/docker/ecervera/webots-docker)

**Comment by psychemedia** [comment]
@ecervera I got the viewer running a demo in the browser by adding the js to the HTML file and commenting out the `$('body').layout()` in the `init()` function (was just trying to simplify...). It doesn't work for me in MyBinder though, which puts me in mind of things like https://github.com/yuvipanda/jupyter-desktop-server which manages to expose a desktop via jupyter-server-proxy as a possible source for a fix?

It also looks like things are running under Py2.7. Is there a py2.7 dependency from ROS? I wonder if it'd be worth building from a more recent Jupyter+ROS base container, eg https://github.com/ccjackchang/Jupyter-ROS or https://github.com/frankjoshua/docker-ros-jupyter maybe?

[I guess this discussion is better as in issue in `Webots-Docker` repo?]
